### ISSUE TITLE
Referencers are resolved only once

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane-runtime#250] opened 2021-03-01 13:50 UTC
### What problem are you facing?

I created a `DBSubnetGroup` with a single element `subnetIdRefs` array. It resolved the reference, reconciled but apparently a single subnet wasn't enough to create a DB Subnet Group in AWS: `DBSubnetGroupDoesNotCoverEnoughAZs:
      DB Subnet Group doesn''t meet availability zone coverage requirement. Please
      add subnets to cover at least 2 availability zones. Current coverage: 1`

Then I created another `Subnet` and added it to the `subnetIdRefs`. But there is no change; the list of actual subnetIds `subnetIds` still had only one element. The reference resolver didn't try to resolve my new referenced object.

### How could Crossplane help solve your problem?

I'd expect the `subnetIds` to include the new element. Delete & recreate solved this case for me but in case of update-able fields that are referenced, I think we should resolve them in every reconcile and return no-op in case there is no change in the resulting list.

**Comment by negz** [comment] 2021-03-11 08:32
Not resolving references when their target value is set was a conscious design decision; see https://github.com/crossplane/crossplane-runtime/issues/76, which is probably tied up with a bunch of other subtle implementation details that lead to https://github.com/crossplane/crossplane-runtime/pull/151. I suggest if we make any changes here we consider them as part of https://github.com/crossplane/crossplane/issues/1770. Since changing the reference resolution logic has often had subtle unexpected consequences in the past, so I'd prefer to make as few changes as possible.

**Comment by muvaf** [comment] 2021-03-11 09:32
I see that we wanted users to have more control over the reference resolving in https://github.com/crossplane/crossplane-runtime/issues/76 but I'm not sure if control is a good or a necessary thing in this case. I mean I couldn't really come up with a scenario where I change the referencer but not want the target value to change.

The thing that was unexpected for me with this behavior is that consumers of the CRs can not really rely on reference or selector fields and make decisions because the target value might have drifted; either the target value or ref/selector changed by the user. For example, if you build an automation that sets the refs or selectors and take actions with their value, we cannot guarantee that it is effective in reality or truthful. There are roughly two options to make all three fields consistent:
* Look at selector, go change ref. Look at ref, go change target value.
* Resolve selector to ref, delete selector. Resolve ref to target, delete ref. Hence only the target value is present as a result.
  * I don't think anyone would want ref/selector to go away, so that's not really an option.

But both options would require to be done in every reconcile to make the guarantee, though it's worth checking if it'd use the cache and not hit api-server. If it hits the api-server, it may not scale.

Additionally, as a user, it was surprising to not see the effect I wanted when I change the referencer because that's all I interact with most of the time.

**Comment by negz** [comment] 2021-03-11 23:58
> I couldn't really come up with a scenario where I change the referencer but not want the target value to change.

I think the question here is more what should take precedence when the reference and the underlying value are both set. If you're explicitly going in and updating the reference or selector it should be trivial to also clear out the underlying values to signal that you want the change to propagate.

On the other hand, if you have something like a database with a `vpcIDRef` that resolves to `aws:vpc:foobar` at time N, how likely is it that you really want your database to try 'move' to a different VPC automatically without any human intervention from you if the referenced VPC (which may be owned by a different party) is 'deleted' and another with the same name is created in its place.

I do think that a selector populating an _array_ of values (i.e. the scenario that lead to this issue being raised) is a bit of a special case, because we can't tell the difference between "one of the things we want to depend on is ready" and "all of the things we want to depend on is ready".

> it's worth checking if it'd use the cache and not hit api-server. If it hits the api-server, it may not scale.

I'm not really worried about performance here, so much as I'm worried about more folks leaning into things changing under folks feet.

**Comment by muvaf** [comment] 2021-03-12 15:32
> I think the question here is more what should take precedence when the reference and the underlying value are both set.

I'm not sure if this is the thing we should be worried though. What I want to achieve at a high level is that there should be consistency between the fields so that I can rely on them. selector>ref>value precedence is just the way to do it. For example, if there was a state where going from value>ref>selector would make sense, that'd also be fine because you know that when you look at the resource, the fields are trusted to be used.

> If you're explicitly going in and updating the reference or selector it should be trivial to also clear out the underlying values to signal that you want the change to propagate.

I'm not sure about this one. When you do `kubectl apply` or some kind of patching with automation tools with the new ref, the target value isn't removed. So, you always have to pass in `vpcId: ""` in your YAMLs to make sure ref is taken into account or you need to do an imperative edit operation.

> if you have something like a database with a vpcIDRef that resolves to aws:vpc:foobar at time N, how likely is it that you really want your database to try 'move' to a different VPC automatically without any human intervention from you if the referenced VPC (which may be owned by a different party) is 'deleted' and another with the same name is created in its place.

VPC is one example though and it's immutable. There are many fields that are referenced and also mutable. For example the `IAMRole` of a service instance or a new `SecurityGroup` you'd like to add to the list of security groups of a certain resource, or just changing the single security group of the resource etc. I think the likeliness here is defined by immutability.

Regarding recreation of the referenced resource, I think this case is discarded by referencer struct by design, i.e. if we want to take that into account, then UID of the referenced resource should be included in the reference either as input or added by the resolver once it's resolved.

> we can't tell the difference between "one of the things we want to depend on is ready" and "all of the things we want to depend on is ready"

If I understood what you mean, [here](https://github.com/crossplane/crossplane-runtime/blob/f2440d9/pkg/reference/reference.go#L186) we return error if the value cannot be fetched from at least one of the resources.

Anyway, we have not received so much feedback from the community regarding this so it may not be as much of a problem as I think or just one that will surface with more managed resources and use cases. We can revisit if folks start to hit this frequently.

**Comment by iAnomaly** [comment] 2021-04-09 23:02
**Carl Henrik Lunde** pointed me to this issue while helping me troubleshoot an `IAMRolePolicyAttachment`'s `spec.forProvider.roleNameSelector` not updating to a change in `crossplane.io/external-name` on a `IAMRole`.

My feedback as a user was this behavior was entirely unintuitive to me and I spent hours fiddling with my Composition and patches trying to determine why this was never updating. Crossplane is incredibly attractive and I'm vetting it at my organization for slowing replacing Terraform, but seemingly little design decisions like this can have a major impact on adoption. Namely, now that I understand the reference resolution processes is essentially one-time at creation, I'm scared of a very real eventuality in production where we need to update a `crossplane.io/external-name` on the Managed Resource to import an external resource assuming it wasn't named/reference correctly when the Composite was first created. It seems my only option at this juncture is to delete the Claim, Composite and ultimately the Managed Resource with the `Orphan` `deletionPolicy` and recreate them all again to update the `spec.forProvider.roleNameSelector` resolved value.

I also want to contribute to your discussing above with my intuitions/opinions. Generally, I align more with what @muvaf is proposing:
> I'm not sure if this is the thing we should be worried though. What I want to achieve at a high level is that there should be consistency between the fields so that I can rely on them. selector>ref>value precedence is just the way to do it. For example, if there was a state where going from value>ref>selector would make sense, that'd also be fine because you know that when you look at the resource, the fields are trusted to be used.

I agree with this very strongly; in fact it feels that this is the value proposition of Crossplane (and Kubernetes Controller paradigm) that makes it fundamentally different from the _applied_ paradigm of Terraform, CloudFront, etc. I want and expect changes to propagate and be reconciled across my resource layer cake even if I'm using indirection like selectors and references.

>VPC is one example though and it's immutable. There are many fields that are referenced and also mutable. For example the IAMRole of a service instance or a new SecurityGroup you'd like to add to the list of security groups of a certain resource, or just changing the single security group of the resource etc. I think the likeliness here is defined by immutability.
Regarding recreation of the referenced resource, I think this case is discarded by referencer struct by design, i.e. if we want to take that into account, then UID of the referenced resource should be included in the reference either as input or added by the resolver once it's resolved.

Again, I agree with this. @negz , I would even take it a step further and say if a database vpcIDRef was mutable that yes, it would make sense to me that if said reference changed, the database would `move` _without human intervention_. Don't get me wrong, there is plenty of operational considerations for "platform builders" to plan for here: like any interface contract, a VPC reference used by a database needs to maintain backwards compatibility or at least not change unexpectedly or unintentionally. However, I feel like this falls more on the shoulders on the platform builder's intention than for Crossplane to try and protect against. Maybe there is room for some middle ground here where static/one-time reference resolution can be opted-in to for specific delicate stateful cases but not by default?

Happy to discuss more as needed. Thanks to you both.

**Comment by muvaf** [comment] 2021-04-11 14:27
> It seems my only option at this juncture is to delete the Claim, Composite and ultimately the Managed Resource with the Orphan deletionPolicy and recreate them all again to update the spec.forProvider.roleNameSelector resolved value.

FWIW, if you delete `spec.forProvider.roleNameRef` and `spec.forProvider.roleName`, it will try to resolve the references again starting from the selector. So there is a workaround but maybe not as intuitive.

>  pointed me to this issue while helping me troubleshoot an IAMRolePolicyAttachment's spec.forProvider.roleNameSelector not updating to a change in crossplane.io/external-name on a IAMRole.

Just so you know, we never account for change in the external name annotation. It's assumed that the managed resource is a very tight representation of the external resource and the ID of a resource does not change. If you're changing the external-name of an existing resource, you might run into other unexpected problems.

However, there could be a case where you are importing an existing resource and the ID you entered is wrong, so you'd like to fix it, but referencers are already resolved because the resolver doesn't look at whether the resource is _ready_ or not; it resolves immediately when it finds a non-empty string in the target field of the target resource. So you'd need to correct the ID in the external-name annotation and find whoever is referencing that resource and delete the ref & selector fields. We had an issue somewhere related to resolving only after the resource reports `Ready: True`, which would make this case less laborious to fix but I couldn't find it. Is that the scenario you're hitting?

**Comment by iAnomaly** [comment] 2021-04-12 16:31
> FWIW, if you delete spec.forProvider.roleNameRef and spec.forProvider.roleName, it will try to resolve the references again starting from the selector. So there is a workaround but maybe not as intuitive.

Ah, good to know; thanks. Certainly cleaner than deleting the entire Claim/Composite/Managed chain and recreating.

> We had an issue somewhere related to resolving only after the resource reports Ready: True, which would make this case less laborious to fix but I couldn't find it. Is that the scenario you're hitting?

Exactly the scenario I'm hitting and afraid of longer term with imports as people make mistakes. Thanks for these suggestions @muvaf.

Still want to +1 for the idea of selector>ref>value reconciling continuously instead of just at creation.

**Comment by larhauga** [comment] 2021-04-15 06:12
I just have to say :+1: for resolving references all the time, if its possible :) 
I would expect this to be the least surprising behavior in kubernetes.

We are hitting this problem when trying to remove securitygroups with references.
We have an [application with sg] that is referenced by a [redis with sg]. Since the redis sg does not reconcile the app sg, we are not able to remove the application sg. I think resolving references all the time would make this deletion process a lot smoother.

**Comment by chlunde** [comment] 2021-09-03 20:46
I think especially for `ResolveMultiple` it doesn't make sense to not resolve constantly. If you only resolve once, isn't it a race condition when creating multiple objects at the same time? If you create four objects, A, Ref1, Ref2, Ref3, with A selecting Ref1/2/3 using labels. Maybe it will select Ref1 only, maybe Ref1, Ref2 - or maybe all, it depends on when A is reconciled?

**Comment by muvaf** [comment] 2021-09-04 15:11
@chlunde hmm that's a really good point. Nowadays, I'm less eager about continuously syncing due to the cost but it seems like we may have to do it at least in `ResolveMultiple`.

The original issue is also about a case of multiple references, so we might be able to get away with doing it only in `ResolveMultiple` though that'd introduce inconsistency to how we expect users to think about reference resolving.

**Comment by BronzeDeer** [comment] 2022-03-01 21:13
I'd also like to put in my +1 towards the "sync all the time" model. I'm currently evaluating using Crossplane in a GitOps Setting with ArgoCD. One of the most attractive things about the general kubernetes ecosystem and the controller/operator pattern is that I can change the desired state in one layer and expect the controllers/operators to make the necessary changes in the lower layers to reflect that desired state exactly (unless I try to change something explicitly immutable, in which case I'd expect an error to be propagated to the layer above.

Without continuous reconciliation of everything not explicitly immutable. all changes would need to be Delete -> Recreate, or Orphan and Re-adopt, lest I risk configuration drift between the desired state in the managed resources and the actual state in the  external resource with little to no way of knowing. If everything is delete & recreate, a lot of the benefits of ArgoCD are lost

**Comment by AnaMariaMoga** [comment] 2022-03-11 12:53
Resolving references all the time or when the synced status is false **would help a lot**. 

I am working on a Crossplane Provider and a lot of resources are referenced by other resources. If one resource of the block is deleted by mistake and recreated (new uuid --> new external name of the CR), the reference is not resolved again (since it already contains the old `uuid`). It would be great to have a way to resolve the reference all the time or if the synced condition is false.

**Closed** 2022-06-13 15:27 UTC
Labels: enhancement
